apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1 
      - op: replace
        path: /spec/maxReplicas
        value: 10
    target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler