# ----------------------------
# Deployment
# ----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: acrdevassessmentacr.azurecr.io/hello-node:23  # placeholder
          ports:
            - containerPort: 3000

---
# ----------------------------
# ClusterIP Service (internal)
# ----------------------------
apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
spec:
  type: ClusterIP
  selector:
    app: hello-node
  ports:
    - port: 80
      targetPort: 3000

---
# ----------------------------
# Ingress with TLS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: host1.domain.ext
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-node-service
            port:
              number: 80

                  
