# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  ACR_NAME: acrdevassessmentacr     # 🔹 Replace with your ACR name (without .azurecr.io)
  IMAGE_NAME: hello-node       # 🔹 Replace with your app/image name
  RESOURCE_GROUP: rg-dev-assessment        # 🔹 Replace with your RG
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AKS_NAME: aks-dev-assessment
  K8S_NAMESPACE: Node
  
jobs:
  build:
    permissions:
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # 🔹 Authenticate with Azure using Service Principal
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ env.AZURE_CLIENT_SECRET }}

    # 🔹 Log in to ACR
    - name: Log in to ACR
      run: |
        az acr login --name $ACR_NAME

    # 🔹 Set BUILD_ID (using GitHub Run Number)
    - name: Set Build ID
      run: echo "BUILD_ID=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    # 🔹 Build Docker image
    - name: Build Docker image
      run: |
        cd src/
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${BUILD_ID} .
           

    # 🔹 Push Docker image
    - name: Push Docker image
      run: |
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${BUILD_ID}

    # (Optional) Output image tag
    - name: Print Image Tag
      run: echo "Pushed image:$ACR_NAME.azurecr.io/$IMAGE_NAME:${BUILD_ID}"

  deploy-to-k8s:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Get AKS credentials
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AKS_NAME }} --overwrite-existing

      # Replace IMAGE_TAG in manifest template
      - name: Prepare manifest
        run: |
          IMAGE_TAG=${{ env.BUILD_ID }}
          sed "s/\${IMAGE_TAG}/$IMAGE_TAG/g" deployment.yml

      # Apply manifest to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout status deployment/hello-node -n ${{ env.K8S_NAMESPACE }}    
